Fix build with GCC 11 onwards
GCC 11 changed header dependencies. It now requires to explicitly
include the '<limits>' header for using 'std::numeric_limits'.

Commit 30a6c68bc3 broke build with GCC 11 and GCC 12, since it
removes some '#include' directives which satisfied the '<limits>'
header with previous versions of GCC, giving the following error:

Source/astcenc_find_best_partitioning.cpp:160:44: error: ‘numeric_limits’ is not a member of ‘std’

[1] https://gcc.gnu.org/gcc-11/porting_to.html